# A first workflow to play around with the editor
name: My First Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  first_job:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: |
          echo "Hello ${{ vars.WHO_TO_GREET }} from ${{ github.actor }}."
          echo "My secret is ${{ secrets.MY_SECRET }}."
          echo "current branch is ${{ github.ref }}."
      - name: Checkout
        uses: actions/checkout@v4.1.0
      - name: List files
        run: tree

  Test:
    name: Test
    runs-on: ubuntu-latest
    environment: Test
    needs: first_job
    steps:
      - name: Echo message
        run: |
          echo "Hello ${{ vars.WHO_TO_GREET }} 👋 from ${{ github.actor }}." 
          sec=$(echo ${{ secrets.MY_SECRET }} | sed 's/./& /g')
          echo "My secret is 🤫 '$sec'."

  Load-Test:
    name: Load-Test
    runs-on: ubuntu-latest
    environment: Load-Test
    needs: first_job
    steps:
      - name: Echo message
        run: |
          echo "Hello ${{ vars.WHO_TO_GREET }} 👋 from ${{ github.actor }}." 
          sec=$(echo ${{ secrets.MY_SECRET }} | sed 's/./& /g')
          echo "My secret is 🤫 '$sec'."

  Production:
    name: Production
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://writeabout.net
    needs: [Test, Load-Test]
    steps:
      - name: Echo message
        run: |
          echo "Hello ${{ vars.WHO_TO_GREET }} 👋 from ${{ github.actor }}."
          sec=$(echo ${{ secrets.MY_SECRET }} | sed 's/./& /g')
          echo "My secret is 🤫 '$sec'."
